name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: cmake qt
      shell: bash
      working-directory: ${{github.workspace}}
      run: ls -las


    #- name: cmake qt
    #  shell: bash
    #  working-directory: ${{github.workspace}}/build
    #  run: cmake -DINTEGRATED_SDK=ON -DCMAKE_BUILD_TYPE=Release -DPACKAGES_DIR=${{github.workspace}}/packages -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/android.toolchain.cmake ${{github.workspace}}

