name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ARCH: arm64-v8a

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: create build dir
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: cmake libs
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=release -DPACKAGES_DIR=${{github.workspace}}/packages -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/source/cmake/android.toolchain.cmake ${{github.workspace}}/source/libs

    - name: make libs
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: make

    - name: list build dir
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ls -las

    #- name: cmake android
    #  shell: bash
    #  working-directory: ${{github.workspace}}/build
    #  run: cmake ../source -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_PREFIX_PATH="${{github.workspace}}/source/libs/${ARCH}/build/dist;${{github.workspace}}/source/libs/build/dist" -DCMAKE_TOOLCHAIN_FILE=../source/cmake/android.toolchain.cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_ANDROID_ARCH_ABI=${ARCH}



