name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ARCH: arm64-v8a

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: create build dir
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: create toolchain dir
      run: cmake -E make_directory ${{github.workspace}}/toolchain

    - name: cmake libs
      shell: bash
      working-directory: ${{github.workspace}}/toolchain
      run: cmake -DCMAKE_BUILD_TYPE=release -DPACKAGES_DIR=${{github.workspace}}/packages -DCMAKE_ANDROID_ARCH_ABI=${ARCH} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/source/cmake/android.toolchain.cmake ${{github.workspace}}/source/libs

    - name: make toolchain
      shell: bash
      working-directory: ${{github.workspace}}/toolchain
      run: make

    - name: list toolchain dist dir
      shell: bash
      working-directory: ${{github.workspace}}/toolchain/dist
      run: ls -las

    - name: cmake android
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ../source -DINTEGRATED_SDK=ON -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_PREFIX_PATH="${{github.workspace}}/toolchain/dist" -DCMAKE_TOOLCHAIN_FILE=../source/cmake/android.toolchain.cmake -DCMAKE_ANDROID_ARCH_ABI=${ARCH}

    - name: make install android
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: make install

    - name: zip build dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: zip -r build.zip build
      
    - name: archive zip
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{github.workspace}}/build.zip

